source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins
gem "just-the-docs"

# Plugins
group :jekyll_plugins do
  gem "jekyll-default-layout"
  gem "jekyll-optional-front-matter"
  gem "jekyll-readme-index"
  gem "jekyll-titles-from-headings"
  gem "jekyll-sitemap"
  gem "jekyll-feed"
end
